name: Build and Publish to PyPI

on: push
# Triggers when a release is published

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Build distribution
      run: poetry build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v_018
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
